#pragma once

#include <map>

#ifdef GBA_GUI_COMMANDS_LIST
static_assert(false, "GBA_GUI_COMMANDS_LIST already defined, header probably included twice");
#endif
#ifdef GBA_GUI_COMMANDS_MAPPING
static_assert(false, "GBA_GUI_COMMANDS_MAPPING already defined, header probably included twice");
#endif
#ifdef GBA_GUI_COMMANDS_END_OF_LIST
static_assert(false, "GBA_GUI_COMMANDS_END_OF_LIST already defined, header probably included twice");
#endif

#define GBA_GUI_COMMANDS_LIST \
	GBA_GUI_COMMANDS_MAPPING(ControlsUp)\
	GBA_GUI_COMMANDS_MAPPING(ControlsDown)\
	GBA_GUI_COMMANDS_MAPPING(ControlsLeft)\
	GBA_GUI_COMMANDS_MAPPING(ControlsRight)\
	GBA_GUI_COMMANDS_MAPPING(ControlsMotionUp)\
	GBA_GUI_COMMANDS_MAPPING(ControlsMotionDown)\
	GBA_GUI_COMMANDS_MAPPING(ControlsMotionLeft)\
	GBA_GUI_COMMANDS_MAPPING(ControlsMotionRight)\
	GBA_GUI_COMMANDS_MAPPING(ControlsA)\
	GBA_GUI_COMMANDS_MAPPING(ControlsB)\
	GBA_GUI_COMMANDS_MAPPING(ControlsL)\
	GBA_GUI_COMMANDS_MAPPING(ControlsR)\
	GBA_GUI_COMMANDS_MAPPING(ControlsSelect)\
	GBA_GUI_COMMANDS_MAPPING(ControlsStart)\
	GBA_GUI_COMMANDS_MAPPING(ControlsSpeed)\
	GBA_GUI_COMMANDS_MAPPING(ControlsScreenCapture)\
	GBA_GUI_COMMANDS_MAPPING(FileOpenGameboyAdvance)\
	GBA_GUI_COMMANDS_MAPPING(FileOpenGameboy)\
	GBA_GUI_COMMANDS_MAPPING(FileRecent01)\
	GBA_GUI_COMMANDS_MAPPING(FileRecent02)\
	GBA_GUI_COMMANDS_MAPPING(FileRecent03)\
	GBA_GUI_COMMANDS_MAPPING(FileRecent04)\
	GBA_GUI_COMMANDS_MAPPING(FileRecent05)\
	GBA_GUI_COMMANDS_MAPPING(FileRecent06)\
	GBA_GUI_COMMANDS_MAPPING(FileRecent07)\
	GBA_GUI_COMMANDS_MAPPING(FileRecent08)\
	GBA_GUI_COMMANDS_MAPPING(FileRecent09)\
	GBA_GUI_COMMANDS_MAPPING(FileRecent10)\
	GBA_GUI_COMMANDS_MAPPING(FileSave)\
	GBA_GUI_COMMANDS_MAPPING(FileSaveGame01)\
	GBA_GUI_COMMANDS_MAPPING(FileSaveGame02)\
	GBA_GUI_COMMANDS_MAPPING(FileSaveGame03)\
	GBA_GUI_COMMANDS_MAPPING(FileSaveGame04)\
	GBA_GUI_COMMANDS_MAPPING(FileSaveGame05)\
	GBA_GUI_COMMANDS_MAPPING(FileSaveGame06)\
	GBA_GUI_COMMANDS_MAPPING(FileSaveGame07)\
	GBA_GUI_COMMANDS_MAPPING(FileSaveGame08)\
	GBA_GUI_COMMANDS_MAPPING(FileSaveGame09)\
	GBA_GUI_COMMANDS_MAPPING(FileSaveGame10)\
	GBA_GUI_COMMANDS_MAPPING(FileLoad)\
	GBA_GUI_COMMANDS_MAPPING(FileLoadGame01)\
	GBA_GUI_COMMANDS_MAPPING(FileLoadGame02)\
	GBA_GUI_COMMANDS_MAPPING(FileLoadGame03)\
	GBA_GUI_COMMANDS_MAPPING(FileLoadGame04)\
	GBA_GUI_COMMANDS_MAPPING(FileLoadGame05)\
	GBA_GUI_COMMANDS_MAPPING(FileLoadGame06)\
	GBA_GUI_COMMANDS_MAPPING(FileLoadGame07)\
	GBA_GUI_COMMANDS_MAPPING(FileLoadGame08)\
	GBA_GUI_COMMANDS_MAPPING(FileLoadGame09)\
	GBA_GUI_COMMANDS_MAPPING(FileLoadGame10)\
	GBA_GUI_COMMANDS_MAPPING(FilePause)\
	GBA_GUI_COMMANDS_MAPPING(FileReset)\
	GBA_GUI_COMMANDS_MAPPING(FileScreenCapture)\
	GBA_GUI_COMMANDS_MAPPING(FileRomInformation)\
	GBA_GUI_COMMANDS_MAPPING(FileToggleMenu)\
	GBA_GUI_COMMANDS_MAPPING(FileClose)\
	GBA_GUI_COMMANDS_MAPPING(FileExit)\
	GBA_GUI_COMMANDS_MAPPING(OptionsVideoVSync)\
	GBA_GUI_COMMANDS_MAPPING(OptionsVideoX1)\
	GBA_GUI_COMMANDS_MAPPING(OptionsVideoX2)\
	GBA_GUI_COMMANDS_MAPPING(OptionsVideoX3)\
	GBA_GUI_COMMANDS_MAPPING(OptionsVideoX4)\
	GBA_GUI_COMMANDS_MAPPING(OptionsVideoFullScreen)\
	GBA_GUI_COMMANDS_MAPPING(OptionsFrameSkipAutomatic)\
	GBA_GUI_COMMANDS_MAPPING(OptionsFrameSkip0)\
	GBA_GUI_COMMANDS_MAPPING(OptionsFrameSkip1)\
	GBA_GUI_COMMANDS_MAPPING(OptionsFrameSkip2)\
	GBA_GUI_COMMANDS_MAPPING(OptionsFrameSkip3)\
	GBA_GUI_COMMANDS_MAPPING(OptionsFrameSkip4)\
	GBA_GUI_COMMANDS_MAPPING(OptionsFrameSkip5)\
	GBA_GUI_COMMANDS_MAPPING(OptionsFrameSkip6)\
	GBA_GUI_COMMANDS_MAPPING(OptionsFrameSkip7)\
	GBA_GUI_COMMANDS_MAPPING(OptionsFrameSkip8)\
	GBA_GUI_COMMANDS_MAPPING(OptionsFrameSkip9)\
	GBA_GUI_COMMANDS_MAPPING(OptionsFilterNormal)\
	GBA_GUI_COMMANDS_MAPPING(OptionsFilterBilinear)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorDirectories)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorPauseWhenInactive)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorSpeedToggle)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorAutomaticIPS)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorRealTimeClock)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorRewindInterval)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorSpeedNone)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorSpeedPercentage)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorSpeedDetailed)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorSpeedTransparent)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorSaveAutomatic)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorSaveEEPROM)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorSaveSRAM)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorSaveFlash)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorSaveEEPROMAndSensor)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorSaveNone)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorSaveFlash64K)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorSaveFlash128K)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorSaveEnhancedDetection)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorUseBIOSFile)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorSkipBIOSFile)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorSelectBIOSFile)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorPNGFormat)\
	GBA_GUI_COMMANDS_MAPPING(OptionsEmulatorBMPFormat)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundOn)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundMute)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundOff)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundEcho)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundLowPass)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundReverseStereo)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundChannel1)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundChannel2)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundChannel3)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundChannel4)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundDirectSoundA)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundDirectSoundB)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSound11Khz)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSound22Khz)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSound44Khz)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundVolumeQuarter)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundVolumeHalf)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundVolume1x)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundVolume2x)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundVolume3x)\
	GBA_GUI_COMMANDS_MAPPING(OptionsSoundVolume4x)\
	GBA_GUI_COMMANDS_MAPPING(OptionsGameboyBorder)\
	GBA_GUI_COMMANDS_MAPPING(OptionsGameboyBorderAutomatic)\
	GBA_GUI_COMMANDS_MAPPING(OptionsGameboyPrinter)\
	GBA_GUI_COMMANDS_MAPPING(OptionsGameboyAutomatic)\
	GBA_GUI_COMMANDS_MAPPING(OptionsGameboyGBA)\
	GBA_GUI_COMMANDS_MAPPING(OptionsGameboyGBC)\
	GBA_GUI_COMMANDS_MAPPING(OptionsGameboySGB)\
	GBA_GUI_COMMANDS_MAPPING(OptionsGameboySGB2)\
	GBA_GUI_COMMANDS_MAPPING(OptionsGameboyGB)\
	GBA_GUI_COMMANDS_MAPPING(OptionsGameboyRealColors)\
	GBA_GUI_COMMANDS_MAPPING(OptionsGameboyGameboyColors)\
	GBA_GUI_COMMANDS_MAPPING(OptionsGameboyColors)\
	GBA_GUI_COMMANDS_MAPPING(OptionsControlsAutofireA)\
	GBA_GUI_COMMANDS_MAPPING(OptionsControlsAutofireB)\
	GBA_GUI_COMMANDS_MAPPING(OptionsControlsAutofireL)\
	GBA_GUI_COMMANDS_MAPPING(OptionsControlsAutofireR)\
	GBA_GUI_COMMANDS_MAPPING(CheatsSearch)\
	GBA_GUI_COMMANDS_MAPPING(CheatsList)\
	GBA_GUI_COMMANDS_MAPPING(CheatsAutomaticallySaveAndLoad)\
	GBA_GUI_COMMANDS_MAPPING(CheatsDisable)\
	GBA_GUI_COMMANDS_MAPPING(CheatsLoad)\
	GBA_GUI_COMMANDS_MAPPING(CheatsSave)\
	GBA_GUI_COMMANDS_MAPPING(ToolsDisassemble)\
	GBA_GUI_COMMANDS_MAPPING(ToolsIO)\
	GBA_GUI_COMMANDS_MAPPING(ToolsMap)\
	GBA_GUI_COMMANDS_MAPPING(ToolsMemory)\
	GBA_GUI_COMMANDS_MAPPING(ToolsOAM)\
	GBA_GUI_COMMANDS_MAPPING(ToolsPalette)\
	GBA_GUI_COMMANDS_MAPPING(ToolsTile)\
	GBA_GUI_COMMANDS_MAPPING(ToolsNextFrame)\
	GBA_GUI_COMMANDS_MAPPING(ToolsDebuggerWait)\
	GBA_GUI_COMMANDS_MAPPING(ToolsDebuggerLoadAndWait)\
	GBA_GUI_COMMANDS_MAPPING(ToolsDebuggerBreak)\
	GBA_GUI_COMMANDS_MAPPING(ToolsDebuggerDisconnect)\
	GBA_GUI_COMMANDS_MAPPING(ToolsRecordSoundStart)\
	GBA_GUI_COMMANDS_MAPPING(ToolsRecordSoundStop)\
	GBA_GUI_COMMANDS_MAPPING(ToolsRecordAVIStart)\
	GBA_GUI_COMMANDS_MAPPING(ToolsRecordAVIStop)\
	GBA_GUI_COMMANDS_MAPPING(ToolsRecordMovieStart)\
	GBA_GUI_COMMANDS_MAPPING(ToolsRecordMovieStop)\
	GBA_GUI_COMMANDS_MAPPING(ToolsPlayMovieStart)\
	GBA_GUI_COMMANDS_MAPPING(ToolsPlayMovieStop)\
	GBA_GUI_COMMANDS_MAPPING(ToolsRewind)\
	GBA_GUI_COMMANDS_MAPPING(ToolsKeybinds)\
	GBA_GUI_COMMANDS_MAPPING(HelpBugReport)\
	GBA_GUI_COMMANDS_MAPPING(HelpLicense)\
	GBA_GUI_COMMANDS_MAPPING(HelpAbout)\
	GBA_GUI_COMMANDS_END_OF_LIST

namespace gui {

#define GBA_GUI_COMMANDS_MAPPING(X) X,
#define GBA_GUI_COMMANDS_END_OF_LIST _count

	enum class Command {
		GBA_GUI_COMMANDS_LIST
	};

#undef GBA_GUI_COMMANDS_MAPPING
#undef GBA_GUI_COMMANDS_END_OF_LIST

	extern std::map<Command, const char*> COMMAND_NAMES;
}
